package com.aforo.apigee.service.impl;

import com.aforo.apigee.dto.ApigeeCustomer;
import com.aforo.apigee.dto.request.CustomerImportRequest;
import com.aforo.apigee.dto.request.LinkDeveloperRequest;
import com.aforo.apigee.dto.request.SaveConnectionRequest;
import com.aforo.apigee.dto.response.*;
import com.aforo.apigee.gateway.ApigeeGateway;
import com.aforo.apigee.model.ConnectionConfig;
import com.aforo.apigee.model.DeveloperLink;
import com.aforo.apigee.repository.ConnectionConfigRepository;
import com.aforo.apigee.repository.DeveloperLinkRepository;
import com.aforo.apigee.security.TenantContext;
import com.aforo.apigee.service.InventoryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class InventoryServiceImpl implements InventoryService {
    
    private final ApigeeGateway apigeeGateway;
    private final ConnectionConfigRepository connectionConfigRepository;
    private final DeveloperLinkRepository developerLinkRepository;
    private final RestTemplate restTemplate;
    
    @Value("${aforo.apigee.org}")
    private String defaultOrg;
    
    @Value("${aforo.services.customer}")
    private String customerServiceUrl;
    
    @Override
    @Transactional
    public ConnectionResponse saveAndTestConnection(SaveConnectionRequest request) {
        log.info("Saving and testing connection for org: {}", request.getOrg());
        
        try {
            // Test connection first (this doesn't need transaction)
            boolean connected = false;
            try {
                connected = apigeeGateway.testConnection(request.getOrg(), request.getServiceAccountJson());
            } catch (Exception e) {
                log.error("Error testing Apigee connection", e);
                return ConnectionResponse.builder()
                        .connected(false)
                        .message("Failed to connect to Apigee: " + e.getMessage())
                        .build();
            }
            
            if (!connected) {
                return ConnectionResponse.builder()
                        .connected(false)
                        .message("Failed to connect to Apigee org: " + request.getOrg())
                        .build();
            }
            
            // Save or update connection config
            ConnectionConfig config = connectionConfigRepository.findByOrg(request.getOrg())
                    .orElse(new ConnectionConfig());
            
            config.setOrg(request.getOrg());
            config.setEnvsCsv(request.getEnvs());
            config.setAnalyticsMode(request.getAnalyticsMode());
            config.setServiceAccountJson(request.getServiceAccountJson());
            
            // Auto-generate HMAC secret
            if (config.getHmacSecret() == null || config.getHmacSecret().isEmpty()) {
                String autoGeneratedSecret = java.util.UUID.randomUUID().toString();
                config.setHmacSecret(autoGeneratedSecret);
                log.info("Auto-generated HMAC secret for org: {}", request.getOrg());
            }
            
            connectionConfigRepository.save(config);
            connectionConfigRepository.flush(); // Force immediate save
            
            log.info("Connection saved successfully for org: {}", request.getOrg());
            
            return ConnectionResponse.builder()
                    .connected(true)
                    .message("Successfully connected to Apigee org: " + request.getOrg())
                    .organizationName(request.getOrg())
                    .hmacSecret(config.getHmacSecret())
                    .build();
                    
        } catch (Exception e) {
            log.error("Error saving connection", e);
            return ConnectionResponse.builder()
                    .connected(false)
                    .message("Error: " + e.getMessage())
                    .build();
        }
    }
    
    @Override
    public List<ApiProductResponse> getApiProducts(String org) {
        String targetOrg = (org != null && !org.isEmpty()) ? org : defaultOrg;
        log.info("Fetching API products from Apigee org: {}", targetOrg);
        
        List<ApiProductResponse> products = apigeeGateway.listApiProducts(targetOrg);
        
        // Just return the products without auto-importing them
        // The user will select which ones to import and assign product types
        log.info("Fetched {} API products from Apigee", products.size());
        return products;
    }
    
    
    @Override
    public List<DeveloperResponse> getDevelopers(String org) {
        String targetOrg = (org != null && !org.isEmpty()) ? org : defaultOrg;
        log.info("Fetching developers from Apigee org: {}", targetOrg);
        return apigeeGateway.listDevelopers(targetOrg);
    }
    
    @Override
    public List<DeveloperAppResponse> getDeveloperApps(String developerId, String org) {
        String targetOrg = (org != null && !org.isEmpty()) ? org : defaultOrg;
        log.info("Fetching apps for developer: {} from org: {}", developerId, targetOrg);
        return apigeeGateway.listDeveloperApps(targetOrg, developerId);
    }
    
    @Override
    @Transactional
    public void linkDeveloper(String developerId, LinkDeveloperRequest request) {
        log.info("Linking developer {} to Aforo customer {}", developerId, request.getAforoCustomerId());
        
        // Get developer details from Apigee
        List<DeveloperResponse> developers = apigeeGateway.listDevelopers(defaultOrg);
        DeveloperResponse developer = developers.stream()
                .filter(d -> d.getId().equals(developerId))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("Developer not found: " + developerId));
        
        // Create or update link
        DeveloperLink link = developerLinkRepository.findByApigeeDeveloperId(developerId)
                .orElse(new DeveloperLink());
        
        link.setApigeeDeveloperId(developerId);
        link.setEmail(developer.getEmail());
        link.setAforoCustomerId(request.getAforoCustomerId());
        
        developerLinkRepository.save(link);
        
        log.info("Developer link saved successfully");
    }
    
    @Override
    public CustomerSyncResponse syncCustomers() {
        Long orgId = TenantContext.getTenantId();
        log.info("Starting customer sync for organization: {}", orgId);
        
        // Get connection config
        ConnectionConfig config = connectionConfigRepository.findByOrg(defaultOrg)
            .orElseThrow(() -> new RuntimeException("Connection not configured for organization: " + orgId));
        
        // Fetch developers from Apigee
        List<ApigeeCustomer> apigeeCustomers = apigeeGateway.fetchDevelopers(
            config.getOrg(), 
            config.getEnvsCsv().split(",")[0] // Use first environment
        );
        
        log.info("Fetched {} developers from Apigee", apigeeCustomers.size());
        
        int created = 0;
        int updated = 0;
        int failed = 0;
        List<String> errors = new ArrayList<>();
        
        // Import each customer to Customer Service
        for (ApigeeCustomer apigeeCustomer : apigeeCustomers) {
            try {
                CustomerImportRequest importRequest = CustomerImportRequest.builder()
                    .businessEmail(apigeeCustomer.getEmail())
                    .firstName(apigeeCustomer.getFirstName())
                    .lastName(apigeeCustomer.getLastName())
                    .companyName(apigeeCustomer.getOrganizationName())
                    .phoneNumber(null) // Apigee doesn't provide phone
                    .source("APIGEE")
                    .externalId(apigeeCustomer.getDeveloperId())
                    .build();
                
                // Call Customer Service import endpoint
                HttpHeaders headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.set("X-Organization-Id", String.valueOf(orgId));
                
                HttpEntity<CustomerImportRequest> entity = new HttpEntity<>(importRequest, headers);
                
                @SuppressWarnings("unchecked")
                ResponseEntity<Map<String, Object>> response = (ResponseEntity<Map<String, Object>>) (ResponseEntity<?>) restTemplate.exchange(
                    customerServiceUrl + "/v1/api/customers/import",
                    HttpMethod.POST,
                    entity,
                    Map.class
                );
                
                if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                    String status = (String) response.getBody().get("status");
                    if ("CREATED".equals(status)) {
                        created++;
                    } else if ("UPDATED".equals(status)) {
                        updated++;
                    }
                    log.info("Imported customer: {} - {}", apigeeCustomer.getEmail(), status);
                }
                
            } catch (Exception e) {
                failed++;
                String error = String.format("Failed to import customer %s: %s", 
                    apigeeCustomer.getEmail(), e.getMessage());
                errors.add(error);
                log.error(error, e);
            }
        }
        
        log.info("Customer sync completed. Created: {}, Updated: {}, Failed: {}", 
            created, updated, failed);
        
        return CustomerSyncResponse.builder()
            .message("Customer sync completed")
            .totalFetched(apigeeCustomers.size())
            .totalCreated(created)
            .totalUpdated(updated)
            .totalFailed(failed)
            .errors(errors)
            .build();
    }
}
